---
- name: Listen for security events on a webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: "Run job template - block port"
      condition: 
         all: 
           - event.payload.alert.clusterName == "sno1"
           - event.payload.alert.policy.name is search("Exec into Pod")
      action:
        run_job_template:
          name: homelab - block firewall port
          organization: Automation Montreal team
          retries: 1
          delay: 10