---
- name: Listen for security events on a webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: "Run job template - block port"
      condition: event.payload.message != ""
      action:
        debug: